Repository umc6th-tom/Backend, pull requests merged in 2024-08, with the labels that each got.

#112 Feat: 1대1 문의, FAQ 엔티티 매핑 추가 및 오타 수정
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
  src/main/java/umc6/tom/fAQ/model/FAQ.java
  src/main/java/umc6/tom/user/model/User.java
Labels: :sparkles: feature

#113 Feat: FCM controller 수정
  src/main/java/umc6/tom/firebase/controller/FCMController.java
  src/main/java/umc6/tom/firebase/dto/FCMRequestDto.java
Labels: :sparkles: feature

#114 Feat: FCM controller 반환 형식 수정
  src/main/java/umc6/tom/firebase/controller/FCMController.java
  src/main/java/umc6/tom/firebase/converter/FCMConverter.java
  src/main/java/umc6/tom/firebase/dto/FCMRequestDto.java
  src/main/java/umc6/tom/firebase/dto/FCMResponseDto.java
  src/main/java/umc6/tom/firebase/service/FcmTokenService.java
  src/main/java/umc6/tom/firebase/service/PushMessage.java
Labels: :sparkles: feature

#115 Feat: FCM 불필요한 api 삭제
  src/main/java/umc6/tom/firebase/controller/FCMController.java
Labels: :sparkles: feature

#116 Feat: 대댓글 달았을 때 알림 보내기 구현. 댓글 달았을 때 자기자신 글이면 알림 안가게 구현
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
  src/main/java/umc6/tom/firebase/service/FirebaseService.java
  src/main/java/umc6/tom/firebase/service/PushMessage.java
Labels: :sparkles: feature

#117 CICD : 깃허브 액션 동작 브렌치 release로 변경
  .github/workflows/dev_deploy.yml
Labels: :construction_worker: CI/CD

#118 CICD : 배포 테스트
  .DS_Store
Labels: :construction_worker: CI/CD

#119 CICD : elb Redis 추가
  .ebextensions_dev/01-redis.config
  .ebextensions_dev/02-set-timezone.config
  .gitignore
Labels: ⚙ Setting, :construction_worker: CI/CD

#120 CICD : elm redis 추가
  .ebextensions_dev/01-redis.config
  .ebextensions_dev/02-set-timezone.config
  .gitignore
Labels: ⚙ Setting, :construction_worker: CI/CD

#121 CICD : elb Redi 설치코드 삭제 (수정)
  .ebextensions_dev/01-redis.config
  .ebextensions_dev/01-set-timezone.config
Labels: ⚙ Setting, :construction_worker: CI/CD

#122 CICD : elb Redi 설치코드 삭제 (수정)
  .ebextensions_dev/01-redis.config
  .ebextensions_dev/01-set-timezone.config
Labels: ⚙ Setting, :construction_worker: CI/CD

#123 [FEAT] chatgpt 연동 및 메모리 누수방지 코드 수정
  src/main/java/umc6/tom/comment/controller/PinController.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
  src/main/java/umc6/tom/gpt/config/GPTConfig.java
  src/main/java/umc6/tom/gpt/controller/MajorController.java
  src/main/java/umc6/tom/gpt/dto/GptReq.java
  src/main/java/umc6/tom/gpt/dto/GptRes.java
  src/main/java/umc6/tom/gpt/dto/MajorReq.java
  src/main/java/umc6/tom/gpt/dto/MajorRes.java
  src/main/java/umc6/tom/gpt/dto/Message.java
  src/main/java/umc6/tom/gpt/service/FavoriteService.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#124 Feat: 자기자신 게시글 추천, 신고 막는 로직 추가
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#125 Feat: 알림 추적을 위한 board entity 매핑
  src/main/java/umc6/tom/alarm/model/Alarm.java
  src/main/java/umc6/tom/board/model/Board.java
Labels: :sparkles: feature

#126 Feat: 게시판, 댓글, 대댓글 알림 DB반영 로직 추가, 파라미터 수정, 좋아요 알림 추가
  src/main/java/umc6/tom/alarm/converter/AlarmConverter.java
  src/main/java/umc6/tom/alarm/model/enums/Field.java
  src/main/java/umc6/tom/alarm/repository/AlarmRepository.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
  src/main/java/umc6/tom/firebase/controller/FCMController.java
  src/main/java/umc6/tom/firebase/converter/FCMConverter.java
  src/main/java/umc6/tom/firebase/service/PushMessage.java
Labels: :sparkles: feature

#127 Feat: Alarm entity 알림 확인 유무 컬럼 추가
  src/main/java/umc6/tom/alarm/model/Alarm.java
  src/main/java/umc6/tom/alarm/model/enums/IsRead.java
Labels: :sparkles: feature

#128 Feat: Alarm entity 수정 및 알림 api 구현, api path 수정
  src/main/java/umc6/tom/alarm/controller/AlarmController.java
  src/main/java/umc6/tom/alarm/converter/AlarmConverter.java
  src/main/java/umc6/tom/alarm/dto/AlarmRequestDto.java
  src/main/java/umc6/tom/alarm/dto/AlarmResponseDto.java
  src/main/java/umc6/tom/alarm/model/Alarm.java
  src/main/java/umc6/tom/alarm/repository/AlarmRepository.java
  src/main/java/umc6/tom/alarm/service/AlaramService.java
  src/main/java/umc6/tom/alarm/service/AlarmServiceImpl.java
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/AlarmHandler.java
  src/main/java/umc6/tom/board/functionClass/DateCalc.java
  src/main/java/umc6/tom/firebase/controller/FCMController.java
Labels: :sparkles: feature

#131 Refactor : 코드 최적화
  .gitignore
  src/main/java/umc6/tom/alarm/service/AlarmSetServiceImpl.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/util/AmazonS3Util.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#132 Refactor : 코드 최적화
  .gitignore
  src/main/java/umc6/tom/alarm/controller/AlarmController.java
  src/main/java/umc6/tom/alarm/converter/AlarmConverter.java
  src/main/java/umc6/tom/alarm/dto/AlarmRequestDto.java
  src/main/java/umc6/tom/alarm/dto/AlarmResponseDto.java
  src/main/java/umc6/tom/alarm/model/Alarm.java
  src/main/java/umc6/tom/alarm/model/enums/Field.java
  src/main/java/umc6/tom/alarm/model/enums/IsRead.java
  src/main/java/umc6/tom/alarm/repository/AlarmRepository.java
  src/main/java/umc6/tom/alarm/service/AlaramService.java
  src/main/java/umc6/tom/alarm/service/AlarmServiceImpl.java
  src/main/java/umc6/tom/alarm/service/AlarmSetServiceImpl.java
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/AlarmHandler.java
  src/main/java/umc6/tom/board/functionClass/DateCalc.java
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
  src/main/java/umc6/tom/comment/controller/PinController.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
  src/main/java/umc6/tom/firebase/controller/FCMController.java
  src/main/java/umc6/tom/firebase/converter/FCMConverter.java
  src/main/java/umc6/tom/firebase/service/PushMessage.java
  src/main/java/umc6/tom/gpt/config/GPTConfig.java
  src/main/java/umc6/tom/gpt/controller/MajorController.java
  src/main/java/umc6/tom/gpt/dto/GptReq.java
  src/main/java/umc6/tom/gpt/dto/GptRes.java
  src/main/java/umc6/tom/gpt/dto/MajorReq.java
  src/main/java/umc6/tom/gpt/dto/MajorRes.java
  src/main/java/umc6/tom/gpt/dto/Message.java
  src/main/java/umc6/tom/gpt/service/FavoriteService.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
  src/main/java/umc6/tom/util/AmazonS3Util.java
  src/main/resources/application.yml
Labels: 🔨 Refactor

#133 Refactor : DS_Store 파일 삭제
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/umc6/.DS_Store
  src/main/java/umc6/tom/.DS_Store
  src/main/java/umc6/tom/user/.DS_Store
Labels: 🔨 Refactor

#134 Feat : 회원 중복, 아이디, 비밀번호찾기 API 수정
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#135 Feat : 회원 중복, 아이디, 비밀번호찾기 API 수정
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/.DS_Store
  src/main/java/umc6/.DS_Store
  src/main/java/umc6/tom/.DS_Store
  src/main/java/umc6/tom/user/.DS_Store
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature, :construction_worker: CI/CD

#137 Feat: 날씨 포맷 변경 및 불필요한 알림 관련 import 제거
  src/main/java/umc6/tom/alarm/controller/AlarmController.java
  src/main/java/umc6/tom/alarm/dto/AlarmRequestDto.java
  src/main/java/umc6/tom/alarm/service/AlarmServiceImpl.java
  src/main/java/umc6/tom/board/functionClass/DateCalc.java
  src/main/java/umc6/tom/firebase/service/FcmTokenService.java
Labels: :sparkles: feature, 🔨 Refactor

#138 Refactor: 게시판 불 필요한 import 제거
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/dto/BoardRequestDto.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/functionClass/DateCalc.java
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/model/BoardComplaint.java
  src/main/java/umc6/tom/board/model/BoardComplaintPicture.java
  src/main/java/umc6/tom/board/model/BoardLike.java
  src/main/java/umc6/tom/board/model/BoardPicture.java
  src/main/java/umc6/tom/board/repository/BoardComplaintRepository.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/board/repository/PinRepositoryBoard.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: 🔨 Refactor

#141 Refactor: api 경로 명칭 변경
  src/main/java/umc6/tom/firebase/controller/FCMController.java
Labels: 🔨 Refactor

#142 Refactor: FAQ 마이페이지 전체 viewList api 구현
  src/main/java/umc6/tom/fAQ/controller/FAQController.java
  src/main/java/umc6/tom/fAQ/converter/FAQConverter.java
  src/main/java/umc6/tom/fAQ/dto/FAQResponseDto.java
  src/main/java/umc6/tom/fAQ/repository/FAQRepository.java
  src/main/java/umc6/tom/fAQ/service/FAQService.java
  src/main/java/umc6/tom/fAQ/service/FAQServiceImpl.java
Labels: :sparkles: feature

#144 feature: 게시글 수정, 게시물 신고 로직 변경
  src/main/java/umc6/tom/board/model/enums/BoardStatus.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#145 bugfix: 게시글 작성, 수정 오류 fix
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/model/BoardComplaintPicture.java
  src/main/java/umc6/tom/board/model/BoardLike.java
  src/main/java/umc6/tom/board/model/BoardPicture.java
  src/main/java/umc6/tom/board/repository/BoardPictureRepository.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
  src/main/java/umc6/tom/util/AmazonS3Util.java
Labels: 🐞 BugFix

#146 Feat: 자주 묻는 질문 리스트, 검색 api 구현
  src/main/java/umc6/tom/alarm/controller/AlarmController.java
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/FAQHandler.java
  src/main/java/umc6/tom/fAQ/controller/FAQController.java
  src/main/java/umc6/tom/fAQ/repository/FAQRepository.java
  src/main/java/umc6/tom/fAQ/service/FAQService.java
  src/main/java/umc6/tom/fAQ/service/FAQServiceImpl.java
Labels: :sparkles: feature

#147 Feat: entity 게시물 신고 상태 추가, 1대1 문의 상태 추가
  src/main/java/umc6/tom/board/model/BoardComplaint.java
  src/main/java/umc6/tom/board/model/enums/BoardComplaintStatus.java
  src/main/java/umc6/tom/inquiry/model/Inquiry.java
  src/main/java/umc6/tom/inquiry/model/InquiryPicture.java
  src/main/java/umc6/tom/inquiry/model/enums/Status.java
Labels: :sparkles: feature

#149 Deploy : 최신 버전 배포
  src/main/java/umc6/tom/alarm/controller/AlarmController.java
  src/main/java/umc6/tom/alarm/dto/AlarmRequestDto.java
  src/main/java/umc6/tom/alarm/service/AlarmServiceImpl.java
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/FAQHandler.java
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardRequestDto.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/functionClass/DateCalc.java
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/model/BoardComplaint.java
  src/main/java/umc6/tom/board/model/BoardComplaintPicture.java
  src/main/java/umc6/tom/board/model/BoardLike.java
  src/main/java/umc6/tom/board/model/BoardPicture.java
  src/main/java/umc6/tom/board/model/enums/BoardComplaintStatus.java
  src/main/java/umc6/tom/board/model/enums/BoardStatus.java
  src/main/java/umc6/tom/board/repository/BoardComplaintRepository.java
  src/main/java/umc6/tom/board/repository/BoardPictureRepository.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/board/repository/PinRepositoryBoard.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
  src/main/java/umc6/tom/comment/controller/CommentController.java
  src/main/java/umc6/tom/comment/controller/PinController.java
  src/main/java/umc6/tom/comment/converter/CommentConverter.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
  src/main/java/umc6/tom/fAQ/controller/FAQController.java
  src/main/java/umc6/tom/fAQ/converter/FAQConverter.java
  src/main/java/umc6/tom/fAQ/dto/FAQResponseDto.java
  src/main/java/umc6/tom/fAQ/repository/FAQRepository.java
  src/main/java/umc6/tom/fAQ/service/FAQService.java
  src/main/java/umc6/tom/fAQ/service/FAQServiceImpl.java
  src/main/java/umc6/tom/firebase/controller/FCMController.java
  src/main/java/umc6/tom/firebase/service/FcmTokenService.java
  src/main/java/umc6/tom/inquiry/model/Inquiry.java
  src/main/java/umc6/tom/inquiry/model/InquiryPicture.java
  src/main/java/umc6/tom/inquiry/model/enums/Status.java
  src/main/java/umc6/tom/util/AmazonS3Util.java
Labels: 🌏 Deploy

#150 Feat: 관리자페이지 자주 묻는 질문 등록, 수정, 삭제 api구현 및 controller 파라미터 수정
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/comment/controller/CommentController.java
  src/main/java/umc6/tom/comment/controller/PinController.java
  src/main/java/umc6/tom/fAQ/controller/FAQController.java
  src/main/java/umc6/tom/fAQ/controller/RootFAQController.java
  src/main/java/umc6/tom/fAQ/converter/FAQConverter.java
  src/main/java/umc6/tom/fAQ/dto/FAQRequestDto.java
  src/main/java/umc6/tom/fAQ/dto/FAQResponseDto.java
  src/main/java/umc6/tom/fAQ/service/RootFAQService.java
  src/main/java/umc6/tom/fAQ/service/RootFAQServiceImpl.java
Labels: :sparkles: feature

#152 bugfix: 조건문 수정
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: 🐞 BugFix

#153 Deploy : 최신사항 반영
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
  src/main/java/umc6/tom/comment/controller/CommentController.java
  src/main/java/umc6/tom/comment/controller/PinController.java
  src/main/java/umc6/tom/fAQ/controller/FAQController.java
  src/main/java/umc6/tom/fAQ/controller/RootFAQController.java
  src/main/java/umc6/tom/fAQ/converter/FAQConverter.java
  src/main/java/umc6/tom/fAQ/dto/FAQRequestDto.java
  src/main/java/umc6/tom/fAQ/dto/FAQResponseDto.java
  src/main/java/umc6/tom/fAQ/service/RootFAQService.java
  src/main/java/umc6/tom/fAQ/service/RootFAQServiceImpl.java
Labels: :construction_worker: CI/CD

#155 [Feat] 문의 작성, 리스트 조회, 상세 내용 조회 api 구현
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/QNAHandler.java
  src/main/java/umc6/tom/board/functionClass/DateCalc.java
  src/main/java/umc6/tom/config/AmazonConfig.java
  src/main/java/umc6/tom/inquiry/controller/QNAController.java
  src/main/java/umc6/tom/inquiry/converter/QNAConverter.java
  src/main/java/umc6/tom/inquiry/dto/QNARequestDto.java
  src/main/java/umc6/tom/inquiry/dto/QNAResponseDto.java
  src/main/java/umc6/tom/inquiry/model/Inquiry.java
  src/main/java/umc6/tom/inquiry/model/enums/Status.java
  src/main/java/umc6/tom/inquiry/repository/InquiryPictureRepository.java
  src/main/java/umc6/tom/inquiry/repository/InquiryRepository.java
  src/main/java/umc6/tom/inquiry/service/QNAService.java
  src/main/java/umc6/tom/inquiry/service/QNAServiceImpl.java
Labels: :sparkles: feature

#158 [Feat] 사진명 response 형태 변경
  src/main/java/umc6/tom/inquiry/converter/QNAConverter.java
Labels: :sparkles: feature

#159 [Feat] 활동 내역 검색 조회 API ✨
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/repository/BoardLikeRepository.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/comment/dto/CommentBoardDto.java
  src/main/java/umc6/tom/comment/repository/CommentRepository.java
  src/main/java/umc6/tom/comment/repository/PinRepository.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#160 refactor: 게시글 조회 응답 json 키 순서 보기 쉽게 변경
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/model/enums/BoardStatus.java
Labels: 🔨 Refactor

#162 [FEAT] GPT 이용한 전공 문제와 답 + 전공검색 API 작성 ✨ feature
  src/main/java/umc6/tom/gpt/controller/MajorController.java
  src/main/java/umc6/tom/gpt/converter/ExampleConverter.java
  src/main/java/umc6/tom/gpt/dto/GptReq.java
  src/main/java/umc6/tom/gpt/dto/GptRes.java
  src/main/java/umc6/tom/gpt/dto/MajorReq.java
  src/main/java/umc6/tom/gpt/function/Function.java
  src/main/java/umc6/tom/gpt/model/Answer.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
Labels: :sparkles: feature

#164 Setting : User 엔티티 수정, 제재 테이블 생성
  src/main/java/umc6/tom/user/model/Prohibit.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/model/mapping/ProhibitBoard.java
Labels: ⚙ Setting

#165 Feat: 문의 답변 등록, 수정, 삭제 api 구현
  src/main/java/umc6/tom/inquiry/controller/RootQNAController.java
  src/main/java/umc6/tom/inquiry/converter/QNAConverter.java
  src/main/java/umc6/tom/inquiry/dto/QNARequestDto.java
  src/main/java/umc6/tom/inquiry/dto/QNAResponseDto.java
  src/main/java/umc6/tom/inquiry/service/RootQNAService.java
  src/main/java/umc6/tom/inquiry/service/RootQNAServiceImpl.java
Labels: :sparkles: feature

#166 Feat: 관리자측 문의 리스트, 문의 검색, 문의 글 보기 api 구현
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/inquiry/controller/RootQNAController.java
  src/main/java/umc6/tom/inquiry/converter/QNAConverter.java
  src/main/java/umc6/tom/inquiry/dto/QNAResponseDto.java
  src/main/java/umc6/tom/inquiry/repository/InquiryRepository.java
  src/main/java/umc6/tom/inquiry/service/RootQNAService.java
  src/main/java/umc6/tom/inquiry/service/RootQNAServiceImpl.java
Labels: :sparkles: feature

#167 Feat: 좋아요 기준 댓글 15-> 20개 이상으로 변경
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
Labels: :sparkles: feature

#168 bugfix: 데이터 삽입시 null값 기본값으로 들어가게 수정
  src/main/java/umc6/tom/board/model/BoardComplaint.java
Labels: 🐞 BugFix

#169 Deploy : 최신사항 반영
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/AdminHandler.java
  src/main/java/umc6/tom/apiPayload/exception/handler/ProhibitBoardHandler.java
  src/main/java/umc6/tom/apiPayload/exception/handler/ProhibitHandler.java
  src/main/java/umc6/tom/apiPayload/exception/handler/QNAHandler.java
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/functionClass/DateCalc.java
  src/main/java/umc6/tom/board/model/BoardComplaint.java
  src/main/java/umc6/tom/board/model/enums/BoardStatus.java
  src/main/java/umc6/tom/board/repository/BoardLikeRepository.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
  src/main/java/umc6/tom/comment/dto/CommentBoardDto.java
  src/main/java/umc6/tom/comment/repository/CommentRepository.java
  src/main/java/umc6/tom/comment/repository/PinRepository.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
  src/main/java/umc6/tom/config/AmazonConfig.java
  src/main/java/umc6/tom/gpt/controller/MajorController.java
  src/main/java/umc6/tom/gpt/converter/ExampleConverter.java
  src/main/java/umc6/tom/gpt/dto/GptReq.java
  src/main/java/umc6/tom/gpt/dto/GptRes.java
  src/main/java/umc6/tom/gpt/dto/MajorReq.java
  src/main/java/umc6/tom/gpt/function/Function.java
  src/main/java/umc6/tom/gpt/model/Answer.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
  src/main/java/umc6/tom/inquiry/controller/QNAController.java
  src/main/java/umc6/tom/inquiry/controller/RootQNAController.java
  src/main/java/umc6/tom/inquiry/converter/QNAConverter.java
  src/main/java/umc6/tom/inquiry/dto/QNARequestDto.java
  src/main/java/umc6/tom/inquiry/dto/QNAResponseDto.java
  src/main/java/umc6/tom/inquiry/model/Inquiry.java
  src/main/java/umc6/tom/inquiry/model/enums/Status.java
  src/main/java/umc6/tom/inquiry/repository/InquiryPictureRepository.java
  src/main/java/umc6/tom/inquiry/repository/InquiryRepository.java
  src/main/java/umc6/tom/inquiry/service/QNAService.java
  src/main/java/umc6/tom/inquiry/service/QNAServiceImpl.java
  src/main/java/umc6/tom/inquiry/service/RootQNAService.java
  src/main/java/umc6/tom/inquiry/service/RootQNAServiceImpl.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/model/Prohibit.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/model/mapping/ProhibitBoard.java
  src/main/java/umc6/tom/user/repository/ProhibitBoardRepository.java
  src/main/java/umc6/tom/user/repository/ProhibitRepository.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :construction_worker: CI/CD

#193 Feat : 회원제재 수정
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/model/Prohibit.java
  src/main/java/umc6/tom/user/model/Resign.java
  src/main/java/umc6/tom/user/model/mapping/ProhibitBoard.java
  src/main/java/umc6/tom/user/repository/ProhibitBoardRepository.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#194 Feat : 게시글 생성, 수정, 삭제 정지된 계정 로직 추가
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#195 Feat : 관리자, 일반 회원 코드 분리
  src/main/java/umc6/tom/user/controller/RootUserController.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/service/RootUserService.java
  src/main/java/umc6/tom/user/service/RootUserServiceImpl.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#196 Deploy : 24.08.11 최신 변경사항 반영
  src/main/java/umc6/tom/alarm/repository/AlarmRepository.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
  src/main/java/umc6/tom/firebase/service/PushMessage.java
  src/main/java/umc6/tom/user/controller/RootUserController.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/model/Prohibit.java
  src/main/java/umc6/tom/user/model/Resign.java
  src/main/java/umc6/tom/user/model/mapping/ProhibitBoard.java
  src/main/java/umc6/tom/user/repository/ProhibitBoardRepository.java
  src/main/java/umc6/tom/user/service/RootUserService.java
  src/main/java/umc6/tom/user/service/RootUserServiceImpl.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :construction_worker: CI/CD

#197 [Feat] 댓글, 대댓글 이미지 파일 등록 API 수정
  src/main/java/umc6/tom/comment/controller/CommentController.java
  src/main/java/umc6/tom/comment/controller/PinController.java
  src/main/java/umc6/tom/comment/converter/PinConverter.java
  src/main/java/umc6/tom/comment/dto/PinPictureDto.java
  src/main/java/umc6/tom/comment/dto/PinReqDto.java
  src/main/java/umc6/tom/comment/model/CommentPicture.java
  src/main/java/umc6/tom/comment/model/PinLike.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
Labels: :sparkles: feature

#198 Deploy : 24.08.11 최신 변경사항 반영
  src/main/java/umc6/tom/comment/controller/CommentController.java
  src/main/java/umc6/tom/comment/controller/PinController.java
  src/main/java/umc6/tom/comment/converter/PinConverter.java
  src/main/java/umc6/tom/comment/dto/PinPictureDto.java
  src/main/java/umc6/tom/comment/dto/PinReqDto.java
  src/main/java/umc6/tom/comment/model/CommentPicture.java
  src/main/java/umc6/tom/comment/model/PinLike.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
Labels: :sparkles: feature

#199 Feat : 게시글 댓글 유저프로필 사진 추가
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
Labels: :sparkles: feature

#203 [FEAT] 댓글, 대댓글 삭제 API 수정 ✨
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/comment/converter/CommentComplaintConverter.java
  src/main/java/umc6/tom/comment/converter/PinComplaintConverter.java
  src/main/java/umc6/tom/comment/model/Comment.java
  src/main/java/umc6/tom/comment/model/Pin.java
  src/main/java/umc6/tom/comment/model/enums/PinBoardStatus.java
  src/main/java/umc6/tom/comment/repository/PinRepository.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
Labels: 🥰 Accessibility

#206 Feat : 게시글 대댓글 달린 댓글 삭제시 삭제된 댓글로 표시 및 게시글 댓글 대댓글 좋아요 눌렀는지 유무 로직 수정
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/service/BoardService.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#207 [FEAT] 관리자 - 유저 신고된 댓글 조회, 유저 신고된 대댓글 조회 API 작성
  src/main/java/umc6/tom/comment/repository/CommentComplaintRepository.java
  src/main/java/umc6/tom/comment/repository/PinComplaintRepository.java
  src/main/java/umc6/tom/user/controller/RootUserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/RootUserService.java
  src/main/java/umc6/tom/user/service/RootUserServiceImpl.java
Labels: :sparkles: feature

#208 Deploy : 24.08.14 최신 변경사항 반영
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/BoardComplaintHandler.java
  src/main/java/umc6/tom/apiPayload/exception/handler/CommentComplaintHandler.java
  src/main/java/umc6/tom/apiPayload/exception/handler/PinComplaintHandler.java
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/functionClass/DateCalc.java
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/repository/BoardComplaintRepository.java
  src/main/java/umc6/tom/board/service/BoardService.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
  src/main/java/umc6/tom/comment/controller/CommentController.java
  src/main/java/umc6/tom/comment/controller/PinController.java
  src/main/java/umc6/tom/comment/converter/CommentComplaintConverter.java
  src/main/java/umc6/tom/comment/converter/CommentConverter.java
  src/main/java/umc6/tom/comment/converter/PinComplaintConverter.java
  src/main/java/umc6/tom/comment/converter/PinConverter.java
  src/main/java/umc6/tom/comment/dto/PinReportReqDto.java
  src/main/java/umc6/tom/comment/model/Comment.java
  src/main/java/umc6/tom/comment/model/CommentComplaint.java
  src/main/java/umc6/tom/comment/model/CommentLike.java
  src/main/java/umc6/tom/comment/model/Pin.java
  src/main/java/umc6/tom/comment/model/PinComplaint.java
  src/main/java/umc6/tom/comment/model/enums/PinBoardStatus.java
  src/main/java/umc6/tom/comment/repository/CommentComplaintRepository.java
  src/main/java/umc6/tom/comment/repository/CommentPictureRepository.java
  src/main/java/umc6/tom/comment/repository/PinComplaintRepository.java
  src/main/java/umc6/tom/comment/repository/PinPictureRepository.java
  src/main/java/umc6/tom/comment/repository/PinRepository.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
  src/main/java/umc6/tom/gpt/dto/GptRes.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
  src/main/java/umc6/tom/user/controller/RootUserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/RootUserService.java
  src/main/java/umc6/tom/user/service/RootUserServiceImpl.java
Labels: :construction_worker: CI/CD

#209 Feat : 카카오 회원가입 구현
  build.gradle
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/common/controller/RestController.java
  src/main/java/umc6/tom/kakao/controller/KakaoLoginController.java
  src/main/java/umc6/tom/kakao/controller/KakaoLoginPageController.java
  src/main/java/umc6/tom/kakao/dto/KakaoTokenResponseDto.java
  src/main/java/umc6/tom/kakao/dto/KakaoUserInfoResponseDto.java
  src/main/java/umc6/tom/kakao/service/KakaoService.java
  src/main/java/umc6/tom/user/controller/RootUserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/model/Prohibit.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/service/RootUserService.java
  src/main/java/umc6/tom/user/service/RootUserServiceImpl.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/kakao_login_medium_narrow.png
  src/main/resources/templates/login.html
Labels: :sparkles: feature

#210 Deploy : 24.08.15 최신 변경사항 반영
  build.gradle
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/common/controller/RestController.java
  src/main/java/umc6/tom/kakao/controller/KakaoLoginController.java
  src/main/java/umc6/tom/kakao/controller/KakaoLoginPageController.java
  src/main/java/umc6/tom/kakao/dto/KakaoTokenResponseDto.java
  src/main/java/umc6/tom/kakao/dto/KakaoUserInfoResponseDto.java
  src/main/java/umc6/tom/kakao/service/KakaoService.java
  src/main/java/umc6/tom/user/controller/RootUserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/model/Prohibit.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/service/RootUserService.java
  src/main/java/umc6/tom/user/service/RootUserServiceImpl.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/static/kakao_login_medium_narrow.png
  src/main/resources/templates/login.html
Labels: :construction_worker: CI/CD

#212 [FEAT] 관리자 - 신고내역 조회 API 작성 ✨ feature
  src/main/java/umc6/tom/board/repository/BoardComplaintRepository.java
  src/main/java/umc6/tom/comment/repository/CommentComplaintRepository.java
  src/main/java/umc6/tom/comment/repository/PinComplaintRepository.java
  src/main/java/umc6/tom/user/controller/RootUserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/RootUserService.java
  src/main/java/umc6/tom/user/service/RootUserServiceImpl.java
Labels: :sparkles: feature

#213 [FEAT] 유저 전공 조회 api 작성
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#214 [FEAT] GPT 질의 수정 (REQUEST시 MAJOR값 추가)
  src/main/java/umc6/tom/gpt/dto/GptReq.java
  src/main/java/umc6/tom/gpt/dto/MajorReq.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
Labels: :sparkles: feature

#215 bugFix : 관리자 계정 FAQ 파라미터 위치 수정
  src/main/java/umc6/tom/fAQ/service/RootFAQServiceImpl.java
Labels: 🐞 BugFix

#216 Deploy : 24.08.17 최신 변경사항 반영
  src/main/java/umc6/tom/board/repository/BoardComplaintRepository.java
  src/main/java/umc6/tom/comment/repository/CommentComplaintRepository.java
  src/main/java/umc6/tom/comment/repository/PinComplaintRepository.java
  src/main/java/umc6/tom/fAQ/service/RootFAQServiceImpl.java
  src/main/java/umc6/tom/gpt/dto/GptReq.java
  src/main/java/umc6/tom/gpt/dto/MajorReq.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
  src/main/java/umc6/tom/user/controller/RootUserController.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/RootUserService.java
  src/main/java/umc6/tom/user/service/RootUserServiceImpl.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :construction_worker: CI/CD

#218 [FEAT] 메인화면 API 작성, 댓글 , 대댓글 작성시 report커럼 null 에러 해결
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/comment/converter/PinConverter.java
  src/main/java/umc6/tom/comment/model/Comment.java
  src/main/java/umc6/tom/comment/model/Pin.java
  src/main/java/umc6/tom/common/model/Majors.java
  src/main/java/umc6/tom/gpt/controller/MajorController.java
  src/main/java/umc6/tom/gpt/converter/ExampleConverter.java
  src/main/java/umc6/tom/gpt/dto/GptReq.java
  src/main/java/umc6/tom/gpt/dto/MajorReq.java
  src/main/java/umc6/tom/gpt/dto/MajorRes.java
  src/main/java/umc6/tom/gpt/model/Answer.java
  src/main/java/umc6/tom/gpt/repository/AnswerRepository.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
Labels: :sparkles: feature, 🐞 BugFix

#219 [FEAT] 메인화면 API 작성
  src/main/java/umc6/tom/gpt/converter/ExampleConverter.java
  src/main/java/umc6/tom/gpt/dto/MajorRes.java
  src/main/java/umc6/tom/gpt/repository/AnswerRepository.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
Labels: :sparkles: feature

#221 Feature/211
  src/main/java/umc6/tom/apiPayload/exception/handler/ExampleHandler.java
  src/main/java/umc6/tom/gpt/controller/MajorController.java
  src/main/java/umc6/tom/gpt/converter/ExampleConverter.java
  src/main/java/umc6/tom/gpt/dto/ExampleDto.java
  src/main/java/umc6/tom/gpt/dto/GptRes.java
  src/main/java/umc6/tom/gpt/dto/MajorReq.java
  src/main/java/umc6/tom/gpt/dto/MajorRes.java
  src/main/java/umc6/tom/gpt/model/Answer.java
  src/main/java/umc6/tom/gpt/model/Example.java
  src/main/java/umc6/tom/gpt/model/ExampleFavorite.java
  src/main/java/umc6/tom/gpt/repository/ExampleRepository.java
  src/main/java/umc6/tom/gpt/service/FavoriteService.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
  src/main/java/umc6/tom/user/controller/RootUserController.java
  src/main/java/umc6/tom/user/service/RootUserService.java
  src/main/java/umc6/tom/user/service/RootUserServiceImpl.java
Labels: :sparkles: feature

#222 Feat: 메인홈 화면 핫글 유저 전공만 뜨게 변경
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#224 [FIX] 댓글,대댓글 좋아요 API 수정
  src/main/java/umc6/tom/comment/repository/CommentLikeRepository.java
  src/main/java/umc6/tom/comment/repository/PinLikeRepository.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
Labels: :sparkles: feature

#225 Deploy : 24.08.19 최신 변경사항 적용
  src/main/java/umc6/tom/comment/repository/CommentLikeRepository.java
  src/main/java/umc6/tom/comment/repository/PinLikeRepository.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/comment/service/PinService.java
Labels: :construction_worker: CI/CD

#226 [FIX] 즐겨찾기 제거 로직 수정
  src/main/java/umc6/tom/gpt/service/FavoriteService.java
Labels: :sparkles: feature

#227 Deploy : 24.08.21 최신 변경사항 반영
  src/main/java/umc6/tom/gpt/service/FavoriteService.java
Labels: :construction_worker: CI/CD

#229 Feat: 전공예제 튜닝
  src/main/java/umc6/tom/gpt/dto/GptReq.java
Labels: :sparkles: feature
