Repository umc6th-tom/Backend, pull requests merged in 2024-07, with the labels that each got.

#3 [Feat] 환경 변수 설정, 엔티티 기본 설계, 패키지 변경
  build.gradle
  src/main/java/umc6/tom/TomApplication.java
  src/main/java/umc6/tom/common/BaseEntity.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/model/enums/Gender.java
  src/main/java/umc6/tom/user/model/enums/Major.java
  src/main/java/umc6/tom/user/model/enums/SocialType.java
  src/main/java/umc6/tom/user/repository/UserRepository.java
Labels: :sparkles: feature

#6 Setting : API 응답통일
  build.gradle
  src/main/java/umc6/tom/apiPayload/ApiResponse.java
  src/main/java/umc6/tom/apiPayload/code/BaseCode.java
  src/main/java/umc6/tom/apiPayload/code/BaseErrorCode.java
  src/main/java/umc6/tom/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc6/tom/apiPayload/code/ReasonDTO.java
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc6/tom/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc6/tom/apiPayload/exception/GeneralException.java
  src/main/java/umc6/tom/apiPayload/exception/handler/CommonHandler.java
Labels: ⚙ Setting

#7 Setting : application.yml .gitignore 추가
  .gitignore
  gradlew.bat
  src/main/resources/application.yml
Labels: ⚙ Setting

#8 Setting : JWT 토큰 관련 설정 완료
  src/main/java/umc6/tom/security/CustomUserDetailsService.java
  src/main/java/umc6/tom/security/JwtAuthenticationFilter.java
  src/main/java/umc6/tom/security/SecurityUtil.java
  src/main/java/umc6/tom/security/config/JwtTokenProvider.java
  src/main/java/umc6/tom/security/config/SecurityConfig.java
  src/main/java/umc6/tom/security/config/WebSecurityConfig.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/model/enums/Role.java
  src/main/java/umc6/tom/user/service/UserDetailService.java
  src/main/java/umc6/tom/user/service/UserDetailServiceImpl.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: ⚙ Setting

#10 [Feat] Entity 설정
  src/main/java/umc6/tom/alarm/model/Alarm.java
  src/main/java/umc6/tom/alarm/model/enums/Field.java
  src/main/java/umc6/tom/board/Comment/model/Pin.java
  src/main/java/umc6/tom/board/Comment/model/PinComment.java
  src/main/java/umc6/tom/board/Comment/model/PinCommentLike.java
  src/main/java/umc6/tom/board/Comment/model/PinCommentPicture.java
  src/main/java/umc6/tom/board/Comment/model/PinLike.java
  src/main/java/umc6/tom/board/Comment/model/PinPicture.java
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/model/BoardComplaint.java
  src/main/java/umc6/tom/board/model/BoardComplaintPicture.java
  src/main/java/umc6/tom/board/model/BoardLike.java
  src/main/java/umc6/tom/board/model/BoardPicture.java
  src/main/java/umc6/tom/common/enums/Status.java
  src/main/java/umc6/tom/common/model/College.java
  src/main/java/umc6/tom/common/model/Majors.java
  src/main/java/umc6/tom/gpt/model/Answer.java
  src/main/java/umc6/tom/gpt/model/Example.java
  src/main/java/umc6/tom/gpt/model/Favorite.java
  src/main/java/umc6/tom/notice/model/Notice.java
  src/main/java/umc6/tom/notice/model/NoticePicture.java
  src/main/java/umc6/tom/user/model/Resign.java
  src/main/java/umc6/tom/user/model/enums/Colleges.java
  src/main/java/umc6/tom/user/model/enums/Field.java
Labels: :sparkles: feature, ⚙ Setting

#12 Feat : User 관련 엔티티 완성
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/model/enums/Field.java
  src/main/java/umc6/tom/common/enums/Status.java
  src/main/java/umc6/tom/common/model/Majors.java
  src/main/java/umc6/tom/common/model/enums/Status.java
  src/main/java/umc6/tom/user/model/Resign.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/model/enums/Agreement.java
  src/main/java/umc6/tom/user/model/enums/Open.java
Labels: :sparkles: feature, ⚙ Setting

#14 Setting : JwtToken에 userId 삽입
  build.gradle
  src/main/java/umc6/tom/apiPayload/exception/handler/PhoneHandler.java
  src/main/java/umc6/tom/apiPayload/exception/handler/UserHandler.java
  src/main/java/umc6/tom/security/RedisUtil.java
  src/main/java/umc6/tom/security/config/JwtTokenProvider.java
  src/main/java/umc6/tom/security/config/RedisConfig.java
Labels: ⚙ Setting

#16 Setting : User 엔티티의 Status -> UserStatus로 enum 분리
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/model/enums/UserStatus.java
Labels: ⚙ Setting

#18 Feat : 회원가입, 중복확인(닉네임, 아이디), 로그인 API 작성 완료
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/security/KeyUtil.java
  src/main/java/umc6/tom/security/config/JwtTokenProvider.java
  src/main/java/umc6/tom/security/config/SecurityConfig.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/repository/UserRepository.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#20 Feat: AlarmSet의 entity, enum 추가, entity 매핑 관계 수정
  src/main/java/umc6/tom/alarm/model/AlarmSet.java
  src/main/java/umc6/tom/alarm/model/enums/AlarmOnOff.java
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/common/model/Majors.java
  src/main/java/umc6/tom/gpt/model/Answer.java
  src/main/java/umc6/tom/gpt/model/Example.java
  src/main/java/umc6/tom/gpt/model/Favorite.java
Labels: :sparkles: feature

#25 Feat : Entity 설계 변경
  src/main/java/umc6/tom/alarm/model/AlarmSet.java
  src/main/java/umc6/tom/alarm/model/enums/AlarmOnOff.java
  src/main/java/umc6/tom/alarm/model/enums/Field.java
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/model/enums/Field.java
  src/main/java/umc6/tom/common/model/College.java
  src/main/java/umc6/tom/common/model/Majors.java
  src/main/java/umc6/tom/common/model/enums/Colleges.java
  src/main/java/umc6/tom/common/model/enums/Major.java
  src/main/java/umc6/tom/common/model/enums/Status.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/model/enums/Agreement.java
  src/main/java/umc6/tom/user/model/enums/Open.java
  src/main/java/umc6/tom/user/model/enums/SocialType.java
Labels: :sparkles: feature

#27 Bugfix : 엔티티 오류로 DB 제작 안되는 오류 수정
  src/main/java/umc6/tom/common/model/College.java
  src/main/java/umc6/tom/user/model/User.java
Labels: 🐞 BugFix

#28 FEAT : 공지사항 리스트 + Paging , 공지사항 글 확인 API 작성
  src/main/java/umc6/tom/notice/controller/NoticeController.java
  src/main/java/umc6/tom/notice/dto/NoticeDto.java
  src/main/java/umc6/tom/notice/dto/NoticePictureDto.java
  src/main/java/umc6/tom/notice/model/Notice.java
  src/main/java/umc6/tom/notice/model/NoticePicture.java
  src/main/java/umc6/tom/notice/repository/NoticePictureRepository.java
  src/main/java/umc6/tom/notice/repository/NoticeRepository.java
  src/main/java/umc6/tom/notice/service/NoticeService.java
Labels: :sparkles: feature

#30 Feat : 비밀번호 암호화
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#32 Feat : Access, Refresh 토큰 분리 및 Jwt 토큰 형태 변경, Header 에서 userId parsing 가능
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/security/CustomUserDetail.java
  src/main/java/umc6/tom/security/CustomUserDetailsService.java
  src/main/java/umc6/tom/security/ExceptionHandlerFilter.java
  src/main/java/umc6/tom/security/JwtAuthenticationFilter.java
  src/main/java/umc6/tom/security/JwtToken.java
  src/main/java/umc6/tom/security/JwtTokenProvider.java
  src/main/java/umc6/tom/security/KeyUtil.java
  src/main/java/umc6/tom/security/RedisUtil.java
  src/main/java/umc6/tom/security/SecurityUtil.java
  src/main/java/umc6/tom/security/config/JwtTokenProvider.java
  src/main/java/umc6/tom/security/config/RedisConfig.java
  src/main/java/umc6/tom/security/config/SecurityConfig.java
  src/main/java/umc6/tom/security/handler/CustomAccessDeniedHandler.java
  src/main/java/umc6/tom/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/repository/ResignRepository.java
  src/main/java/umc6/tom/user/repository/UserRepository.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature, ⚙ Setting

#34 Feat : 로그아웃 API 구현
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#35 Feat: 모든 게시물 조회, 게시물 좋아요, 게시물 좋아요 제거 구현 및 오류 코드 추가 (사진 미구현)
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/BoardHandler.java
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardRequestDto.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/repository/BoardLikeRepository.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/board/service/BoardService.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#36 Feat : User 엔티티에 대한 nullable, 칼럼 길이 등 속성 수정
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/model/User.java
Labels: :sparkles: feature

#37 Feat : 회원 정보 찾기, 변경 등 API 작성
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#39 Feat : 회원 정보 찾기, 변경 등 API 작성
  src/main/java/umc6/tom/user/controller/UserController.java
Labels: :sparkles: feature

#40 Bugfix : User password 문제 해결
  src/main/java/umc6/tom/user/model/User.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: 🐞 BugFix

#41 Setting : AccessToken 만료시간 변경(개발단계 임시)
  src/main/java/umc6/tom/security/JwtTokenProvider.java
Labels: ⚙ Setting

#42 Feature/31
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/gpt/controller/MajorController.java
  src/main/java/umc6/tom/gpt/converter/ExampleConverter.java
  src/main/java/umc6/tom/gpt/dto/AnswerDto.java
  src/main/java/umc6/tom/gpt/dto/ExampleDto.java
  src/main/java/umc6/tom/gpt/dto/ExampleFavoriteDto.java
  src/main/java/umc6/tom/gpt/model/Answer.java
  src/main/java/umc6/tom/gpt/model/Example.java
  src/main/java/umc6/tom/gpt/model/ExampleFavorite.java
  src/main/java/umc6/tom/gpt/repository/AnswerRepository.java
  src/main/java/umc6/tom/gpt/repository/ExampleFavoriteRepository.java
  src/main/java/umc6/tom/gpt/repository/ExampleRepository.java
  src/main/java/umc6/tom/gpt/service/FavoriteService.java
  src/main/java/umc6/tom/gpt/service/MajorService.java
  src/main/java/umc6/tom/notice/controller/NoticeController.java
  src/main/java/umc6/tom/notice/service/NoticeService.java
  src/main/java/umc6/tom/user/model/User.java
Labels: :sparkles: feature

#44 [FEATURE] 댓글 + 사진 등록 API 구현
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/PinHandler.java
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/repository/PinCommentRepositoryBoard.java
  src/main/java/umc6/tom/comment/controller/CommentController.java
  src/main/java/umc6/tom/comment/converter/PinConverter.java
  src/main/java/umc6/tom/comment/converter/PinPictureConverter.java
  src/main/java/umc6/tom/comment/dto/PinCommentDto.java
  src/main/java/umc6/tom/comment/dto/PinCommentLikeDto.java
  src/main/java/umc6/tom/comment/dto/PinCommentPictureDto.java
  src/main/java/umc6/tom/comment/dto/PinDto.java
  src/main/java/umc6/tom/comment/dto/PinLikeDto.java
  src/main/java/umc6/tom/comment/dto/PinPictureDto.java
  src/main/java/umc6/tom/comment/dto/PinReqDto.java
  src/main/java/umc6/tom/comment/model/Pin.java
  src/main/java/umc6/tom/comment/model/PinComment.java
  src/main/java/umc6/tom/comment/model/PinCommentLike.java
  src/main/java/umc6/tom/comment/model/PinCommentPicture.java
  src/main/java/umc6/tom/comment/model/PinLike.java
  src/main/java/umc6/tom/comment/model/PinPicture.java
  src/main/java/umc6/tom/comment/repository/PinCommentLikeRepository.java
  src/main/java/umc6/tom/comment/repository/PinCommentPictureRepository.java
  src/main/java/umc6/tom/comment/repository/PinCommentRepository.java
  src/main/java/umc6/tom/comment/repository/PinLikeRepository.java
  src/main/java/umc6/tom/comment/repository/PinPictureRepository.java
  src/main/java/umc6/tom/comment/repository/PinRepository.java
  src/main/java/umc6/tom/comment/service/CommentService.java
  src/main/java/umc6/tom/gpt/dto/AnswerDto.java
  src/main/java/umc6/tom/gpt/dto/ExampleFavoriteDto.java
Labels: :sparkles: feature

#47 Feat : 쿠키를 사용한 refreshToken 저장 기능 구현
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/security/JwtTokenProvider.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/RefreshConverter.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/model/RefreshToken.java
  src/main/java/umc6/tom/user/repository/RefreshTokenRepository.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
  src/main/java/umc6/tom/util/CookieUtil.java
Labels: :sparkles: feature

#48 Feat : 로그아웃 시 쿠키의 refreshToken 정보 만료, AccessToken 시간 늘림(임시)
  src/main/java/umc6/tom/security/JwtTokenProvider.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#49 bug : 버그 수정 및 예외 처리 추가
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: bug, :sparkles: feature

#51 Feat : 활동내역 공개 on/off API, AlarmSet 관련 모든 API 제작
  src/main/java/umc6/tom/alarm/controller/AlarmSetController.java
  src/main/java/umc6/tom/alarm/converter/AlarmSetConverter.java
  src/main/java/umc6/tom/alarm/model/AlarmSet.java
  src/main/java/umc6/tom/alarm/repository/AlarmSetRepository.java
  src/main/java/umc6/tom/alarm/service/AlarmSetService.java
  src/main/java/umc6/tom/alarm/service/AlarmSetServiceImpl.java
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/AlarmSetHandler.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#52 Feat: 핫한 게시판 조회,검색 및 메인 게시팜 홈 조회, 게시물 수정 api 구현
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardRequestDto.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/model/BoardPicture.java
  src/main/java/umc6/tom/board/repository/BoardPictureRepository.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/board/service/BoardService.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#53 [PEATURE] Comment 댓글 수정 API 작성
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/comment/controller/CommentController.java
  src/main/java/umc6/tom/comment/converter/PinConverter.java
  src/main/java/umc6/tom/comment/converter/PinPictureConverter.java
  src/main/java/umc6/tom/comment/dto/PinDto.java
  src/main/java/umc6/tom/comment/dto/PinReqDto.java
  src/main/java/umc6/tom/comment/model/Pin.java
  src/main/java/umc6/tom/comment/repository/PinPictureRepository.java
  src/main/java/umc6/tom/comment/service/CommentService.java
Labels: :sparkles: feature

#54 Feat : 휴대폰 인증 기능 구현
  build.gradle
  src/main/java/umc6/tom/alarm/service/AlarmSetServiceImpl.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoReq.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
  src/main/java/umc6/tom/util/SmsUtil.java
Labels: :sparkles: feature

#59 Setting: Swagger dependency 추가, Config 구현
  build.gradle
  src/main/java/umc6/tom/config/SwaggerConfig.java
Labels: ⚙ Setting

#60 Feat: Board entity 상태 값 수정
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/model/enums/BoardStatus.java
Labels: :sparkles: feature

#63 Feat: boardCompaint entity 컬럼 추가
  src/main/java/umc6/tom/board/model/BoardComplaint.java
Labels: :sparkles: feature

#64 Feat: board entity 불필요한 컬럼 삭제
  src/main/java/umc6/tom/board/model/Board.java
Labels: :sparkles: feature

#65 Feat: board entity 불필요한 컬럼 삭제
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/model/BoardComplaint.java
Labels: :sparkles: feature

#66 Feat : RefreshToken 의 저장소로 Redis 사용
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/apiPayload/exception/handler/JwtHandler.java
  src/main/java/umc6/tom/config/RedisConfig.java
  src/main/java/umc6/tom/security/JwtAuthenticationFilter.java
  src/main/java/umc6/tom/security/JwtTokenProvider.java
  src/main/java/umc6/tom/user/converter/RefreshConverter.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/model/RefreshToken.java
  src/main/java/umc6/tom/user/repository/RefreshTokenRepository.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
  src/main/java/umc6/tom/util/RedisUtil.java
Labels: :sparkles: feature

#68 Feat: board entity 수정
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/model/enums/BoardStatus.java
Labels: :sparkles: feature

#69 Feat: board 조회, 삭제, 수정 로직 변경 및 핫한게시판 검색, 게시글 조회 구현
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/model/BoardComplaint.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/board/service/BoardService.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#70 Feat: board repository 수정
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#71 Feat: 게시글 View api 수정
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/functionClass/DateCalc.java
  src/main/java/umc6/tom/comment/model/Pin.java
Labels: :sparkles: feature

#73 CI/CD : ci/cd 파이프라인 구축 및, 환경 설정, healthCheck API 구현
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  .platform/nginx/conf.d/client_max_body_size.conf
  Procfile
  build.gradle
  src/main/java/umc6/tom/common/controller/RestController.java
Labels: :construction_worker: CI/CD

#75 CI/CD : ci/cd 파이프라인 구축 및, 환경 설정, healthCheck API 구현, yml 환경변수 보안 setting
  .gitignore
  src/main/resources/application.yml
Labels: ⚙ Setting, :construction_worker: CI/CD

#77 CI/CD : ci/cd 파이프라인 구축 및, 환경 설정, healthCheck API 구현, yml 환경변수 보안 setting
  .ebextensions_dev/00-makeFiles.config
  .ebextensions_dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .gitignore
  .platform/nginx.conf
  .platform/nginx/conf.d/client_max_body_size.conf
  Procfile
  build.gradle
  src/main/java/umc6/tom/common/controller/RestController.java
  src/main/resources/application.yml
Labels: ⚙ Setting, :construction_worker: CI/CD

#78 [CICD] init
  src/main/java/umc6/tom/common/controller/RestController.java
Labels: :construction_worker: CI/CD

#80 [CICD] test
  .ebextensions_dev/00-makeFiles.config
  .platform/nginx.conf
  .platform/nginx/conf.d/client_max_body_size.conf
  .platform/nginx/nginx.conf
  src/main/resources/application.yml
Labels: :construction_worker: CI/CD

#83 [CICD] deploy.yml 수정
  .ebextensions_dev/00-makeFiles.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  .platform/nginx/nginx.conf
Labels: :construction_worker: CI/CD

#86 Feat: BoardListView 미리보기 사진 변수 추가
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#88 Bugfix : elb 버그 수정
  src/main/java/umc6/tom/util/AmazonS3Util.java
Labels: 🐞 BugFix

#89 Bugfix : elb bugfix
  src/main/java/umc6/tom/config/AmazonConfig.java
  src/main/resources/application.yml
Labels: 🐞 BugFix

#90 CICD : 재배포
  .github/workflows/dev_deploy.yml
  src/.DS_Store
Labels: 🐞 BugFix, :construction_worker: CI/CD

#93 Feat: 글 작성, 글 수정 사진 API 구현, 일부 변수 수정 및 추가
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/repository/BoardComplaintPictureRepository.java
  src/main/java/umc6/tom/board/repository/BoardPictureRepository.java
  src/main/java/umc6/tom/board/service/BoardService.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#94 Feat: 글 작성 dto 수정
  src/main/java/umc6/tom/board/dto/BoardRequestDto.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#96 Feat: swagger multipart/form-data 지원
  src/main/java/umc6/tom/board/converter/MultipartJackson2HttpMessageConverter.java
Labels: :sparkles: feature

#98 Feat: 게시물 등록 관련 dto 등 수정
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/dto/BoardRequestDto.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#99 [FEAT] 활동내역 전체 조회 API 작성 완료 & 좋아요 ENTITY 등록시간 추가
  src/main/java/umc6/tom/board/dto/BoardRequestDto.java
  src/main/java/umc6/tom/board/functionClass/DateCalc.java
  src/main/java/umc6/tom/board/model/Board.java
  src/main/java/umc6/tom/board/model/BoardLike.java
  src/main/java/umc6/tom/board/repository/BoardLikeRepository.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/comment/dto/LikeBoardDto.java
  src/main/java/umc6/tom/comment/dto/PinBoardDto.java
  src/main/java/umc6/tom/comment/model/CommentLike.java
  src/main/java/umc6/tom/comment/model/PinLike.java
  src/main/java/umc6/tom/comment/repository/PinRepository.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#101 Feat: 게시물 관련 dto 등 수정
  src/main/java/umc6/tom/board/controller/BoardRestController.java
Labels: :sparkles: feature

#102 [FEAT] 자기 활동내역 기능별 조회 (내가 쓴글, 내가 쓴 댓글 글, 좋아요 누른 글) API 작성 완료
  src/main/java/umc6/tom/board/repository/BoardLikeRepository.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/comment/repository/PinRepository.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#104 [FEAT] 타인 프로필 조회 상세보기(게시글 리스트, 댓글 작성한 글 리스트) API 작성
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/user/controller/UserController.java
  src/main/java/umc6/tom/user/converter/UserConverter.java
  src/main/java/umc6/tom/user/dto/UserDtoRes.java
  src/main/java/umc6/tom/user/service/UserService.java
  src/main/java/umc6/tom/user/service/UserServiceImpl.java
Labels: :sparkles: feature

#106 Feat: 핫한 게시판 전공 선택 가능 기능 추가
  src/main/java/umc6/tom/board/controller/BoardRestController.java
  src/main/java/umc6/tom/board/repository/BoardRepository.java
  src/main/java/umc6/tom/board/service/BoardService.java
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#107 Feat: 게시물 view에 boardId값 추가
  src/main/java/umc6/tom/board/converter/BoardConverter.java
  src/main/java/umc6/tom/board/dto/BoardResponseDto.java
Labels: :sparkles: feature

#108 Feat: 게시물 삭제, 수정시 버킷에서 실제 데이터 삭제 추가
  src/main/java/umc6/tom/board/service/BoardServiceImpl.java
Labels: :sparkles: feature

#109 Feat: firebase FCM 알림 구현 및 댓글 달릴시 알림 보내기 로직 추가
  build.gradle
  src/main/java/umc6/tom/alarm/controller/AlarmController.java
  src/main/java/umc6/tom/alarm/repository/AlarmSetRepository.java
  src/main/java/umc6/tom/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc6/tom/comment/service/PinService.java
  src/main/java/umc6/tom/firebase/config/FirebaseConfig.java
  src/main/java/umc6/tom/firebase/controller/FCMController.java
  src/main/java/umc6/tom/firebase/converter/FirebaseConverter.java
  src/main/java/umc6/tom/firebase/dto/FCMMessageDto.java
  src/main/java/umc6/tom/firebase/dto/FCMRequestDto.java
  src/main/java/umc6/tom/firebase/service/FcmTokenService.java
  src/main/java/umc6/tom/firebase/service/FirebaseService.java
  src/main/java/umc6/tom/firebase/service/PushMessage.java
  src/main/java/umc6/tom/util/RedisUtil.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#110 Feat: firebase userId 수정
  src/main/java/umc6/tom/firebase/controller/FCMController.java
Labels: :sparkles: feature

#111 Feat: 1대1문의, FAQ entity 구현
  src/main/java/umc6/tom/fAQ/model/FAG.java
  src/main/java/umc6/tom/fAQ/model/enums/Category.java
  src/main/java/umc6/tom/inquiry/model/Inquiry.java
  src/main/java/umc6/tom/inquiry/model/InquiryPicture.java
Labels: :sparkles: feature
